language: ruby
rvm:
  - 2.3.1
test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rspec
